version: '3.1'
services:
  angular:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "npm install && npm install -g @angular/cli@8.3.29 && ng serve --host localhost"
    ports:
      - 9005:9005
